name: UHC
main: com.leontg77.ultrahardcore.Main
version: 1.11.15
author: LeonTG77
description: A private UHC plugin made for ArcticUHC ONLY.
softdepend: [ProtocolLib, Pregenner]

commands:
  arena:
    description: Join the pvp arena.
    aliases: [a, p]
  back:
    description: Teleport to your last location.
  ban:
    description: Ban a player.
  banip:
    description: Ban an ip adress.
    aliases: [ipban]
  board:
    description: Toggle the pregame board.
  border:
    description: View or set the border size.
  broadcast:
    description: Broadcast a message to all players online.
    aliases: [bc, bcast]
  butcher:
    description: Kills all hostile mobs.
    aliases: [ekill, killall]
  config:
    description: Change the game settings.
  chat:
    description: Mute or clear the chat.
    aliases: [c]
  clearinv:
    description: Clear someones inventory.
    aliases: [clear, clearinv, ci]
  clearxp:
    description: Clear someones xp levels.
    aliases: [cxp]
  combatlog:
    description: Check if you are in combat.
    aliases: [ct]
  dq:
    description: Ban someone for 1 game.
  edit:
    description: Edit the sign you are looking at.
  end:
    description: End the game and reset everything.
  feed:
    description: Feed someone.
  fire:
    description: Start the firework show.
  fly:
    description: Toggle someones fly mode.
  g:
    description: Talk in global chat while having spectator chat protection.
  gg:
    description: Alias for '/g gg'.
  gamemode:
    description: Change your gamemode.
    aliases: [gm]
  giveall:
    description: Give everyone online an item.
  give:
    description: Give a player an item.
  heal:
    description: Heal someone.
  health:
    description: View someones health.
    aliases: [h]
  helpop:
    description: Ask staff for help.
  hof:
    description: View the hall of fame.
  hotbar:
    description: Save your arena hotbar.
  ignore:
    description: Ignore a player.
  info:
    description: View information on a player.
  infoip:
    description: View which players who has the given ip.
  invsee:
    description: Opens the targets inventoty.
  kick:
    description: Kick a player.
  list:
    description: Shows a list of online players.
  matchpost:
    description: Get the link of the match post.
    aliases: [post]
  mucoords:
    description: Get the meetup coords for moved middle games.
  ms:
    description: Check someones ping to the server
    aliases: [ping]
  msg:
    description: Msg a player something secret.
    aliases: [t, tell, whisper, m]
  mute:
    description: Mute a player or the chat.
  near:
    description: Check for nearby players.
  parkour:
    description: Restart, leave or go to your last parkour checkpoint.
  pm:
    description: Team chat command.
    aliases: [tc]
  pmores:
    description: Send your ore count to your team.
    aliases: [sendores]
  pmminedores:
    description: Send your mined ore count to your team.
    aliases: [sendminedores]
  pregen:
    description: Pregen a world.
  pvp:
    description: Toggle pvp in a specific world.
  respawn:
    description: Respawn a player.
  random:
    description: Create random teams.
  rank:
    description: Change someones rank.
  reply:
    description: Reply to your latest msg.
    aliases: [r]
  scenario:
    description: Enable and disable scenarios
    aliases: [scen]
  sethealth:
    description: Set the health of a player.
  setmaxhealth:
    description: Set the max health of a player.
  skull:
    description: Spawn a player head.
  specchat:
    description: Talk in the spectator chat.
    aliases: [sc]
  specandstaffchat:
    description: Talk in the spectator + staff chat.
    aliases: [ssc, sschat]
  spectate:
    description: Change your spectator status.
    aliases: [spec]
  setfixedscatterlocation:
    description: Set fixed scatter locations for players.
    aliases: [fsl]
  setspawn:
    description: Set the lobby spawn point.
  speed:
    description: Change your fly/walk speed
  scatter:
    description: Spread all players and freeze them.
    aliases: [spread]
  ac:
    description: Talk in StaffChat.
  scp:
    description: Enable/disable spectator chat protection.
  start:
    description: Start command.
  stats:
    description: View your stats.
  team:
    description: Team command, check usage.
    aliases: [party]
  tempban:
    description: Tempban a player.
    aliases: [tban]
  text:
    description: Spawn a floating text.
  timeleft:
    description: Check the time left.
  timer:
    description: Hotbar timer command.
  tl:
    description: Display your location to your teammates.
    aliases: [sendcoords, pmcoords, teamcoords, teamloc]
  top:
    description: View the top scores for a specific stat.
  tps:
    description: Check the server tps and usage.
    aliases: [lag]
  tp:
    description: Makes you able to teleport as a spectator.
  uhc:
    description: View the game information.
    aliases: [game]
  unban:
    description: Unban a player.
  unbanip:
    description: Unban a ip adress.
    aliases: [ipunban]
  viewdistance:
    description: Set the servers view distance.
    aliases: [vd]
  vote:
    description: Start or end a vote.
  whitelist:
    description: Whitelisting command.
    aliases: [wl]
  world:
    description: Create and manage worlds.
    aliases: [w]
# Scenario Commands.
  alist:
    description: View available achievements to hunt for.
  target:
    description: View your assassins target.
  class:
    description: View your AssaultAndBarrery type.
  listclass:
    description: View who has what AssaultAndBarrery type.
  bp:
    description: Open your backpack.
  barrierworld:
    description: Generate the barrier world scenario.
  btc:
    description: Add or remove someone from the BestBTC list.
  btclist:
    description: View the BestBTC list.
  pve:
    description: Add or remove someone from the BestPvE list.
  pvelist:
    description: View the BestPvE list.
  bigcrack:
    description: Generate the big crack.
  bl:
    description: View the biomeparanoia colors.
  cobble:
    description: Generate the cobble world scenario.
  ore:
    description: View the current blood cycle ore.
  addcaptain:
    description: Add a captain.
  removecaptain:
    description: Remove a captain.
  randomcaptain:
    description: Add a random captain.
  cycle:
    description: Start or stop the choosing.
  choose:
    description: Choose a player.
  chunkapo:
    description: Generate chunk apoclaypse.
  current:
    description: View the current damage type.
  dtime:
    description: View how long you got left of your life.
  flood:
    description: Generate the flooded scenario.
  genie:
    description: Genie command, check usage.
  glassify:
    description: Generate the glass world scenario.
  invert:
    description: Generate the inverted dimentions scenario.
  invertpara:
    description: Generate the inverted parallel scenario.
  kings:
    description: Manage kings.
  molehelp:
    description: View mole commands.
  mcl:
    description: Send your loc to your mole team.
  mcc:
    description: Chat with your mole team.
  mcp:
    description: View your mole team.
  mysteryteams:
    description: Mystery teams command.
    aliases: [mt]
  dodge:
    description: Check the current needed death amount in damage dodgers.
  status:
    description: Check the current resistance type.
  genpyro:
    description: Generate Pyrophobia.
  market:
    description: Manage the slave market scenario.
  bid:
    description: Bid on a player.
  skyores:
    description: Generate the sky ores scenario.
  slimecrack:
    description: Generate the SlimyCrack.
  snowday:
    description: Generate the snowday scenario.
  soul:
    description: Manage soul brother scatter.
  lwcm:
    description: Manage LWCM scatter.
  slist:
    description: View what effects people have.
  super:
    description: Add or remove effects.
  genportal:
    description: Generate the underground parallel scenario.
  underpara:
    description: Generate the underground parallel scenario.
  voidscape:
    description: Generate voidscape.